[boris]
  version = 1

[build.branches-7-10]
  command = [
      ["master", "build", "branches-7-10", "-C", "zodiac-core"]
    , ["master", "build", "branches-7-10", "-C", "zodiac-http-client"]
    , ["master", "build", "branches-7-10", "-C", "zodiac-raw"]
    , ["master", "build", "branches-7-10", "-C", "zodiac-cli"]
    , ["./bin/ci.zodiac-publish-build"]
    , ["master", "build", "branches-7-10", "-C", "zodiac-export"]
    ]

[build.dist-7-10-core]
  command = [["master", "build", "dist-7-10", "-C", "zodiac-core"]]

[build.dist-7-10-http-client]
  command = [["master", "build", "dist-7-10", "-C", "zodiac-http-client"]]

[build.dist-7-10-raw]
  command = [["master", "build", "dist-7-10", "-C", "zodiac-raw"]]

[build.dist-7-10-cli]
  command = [
      ["master", "build", "dist-7-10", "-C", "zodiac-cli"]
    , ["./bin/ci.zodiac-publish-build"]
    ]

[build.dist-7-10-export]
  command = [["master", "build", "dist-7-10", "-C", "zodiac-export"]]

[build.branches-7-10-core]
  command = [["master", "build", "branches-7-10", "-C", "zodiac-core"]]

[build.branches-7-10-http-client]
  command = [["master", "build", "branches-7-10", "-C", "zodiac-http-client"]]

[build.branches-7-10-raw]
  command = [["master", "build", "branches-7-10", "-C", "zodiac-raw"]]

[build.branches-7-10-cli]
  command = [
      ["master", "build", "branches-7-10", "-C", "zodiac-cli"]
    , ["./bin/ci.zodiac-publish-build"]
    ]

[build.branches-7-10-export]
  command = [["master", "build", "branches-7-10", "-C", "zodiac-export"]]

[build.submodules]
  command = [["dangling-refs"]]

[build.submodules-branches]
  command = [["dangling-refs"]]

[build.dist-cabal-test]
  command = [["./bin/ci.cabal-test"]]

[build.branches-cabal-test]
  command = [["./bin/ci.cabal-test"]]

[build.validate]
  command = [["validate-respect"]]

[build.rebased]
  command = [["rebased"]]
